# Generated by Django 4.0.1 on 2022-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
